wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1673868823.737254
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 23
      - 37
      4: 3.8.10
      5: 0.13.7
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.00024034635307470332
